
MAHARASHTRA_CITIES = [
    "Visakhapatnam", "Vijayawada", "Guntur", "Tirupati", "Kakinada", "Rajahmundry", "Nellore", "Delhi",
            "Anantapur", "Kadapa", "Chittoor", "Eluru", "Srikakulam", "Prakasam", "Kurnool", 
            "Vijayanagaram", "Bhimavaram", "Machilipatnam", "Palnadu", "Narsipatnam", "Tanuku", 
            "Yemmiganur", "Tadipatri", "Jammalamadugu", "Peddaganjam", "Araku Valley",
            "Itanagar", "Tawang", "Bomdila", "Ziro", "Naharlagun", "Pasighat", "Roing", "Changlang", 
            "Tezu", "Daporijo",
            "Guwahati", "Dibrugarh", "Silchar", "Jorhat", "Nagaon", "Tezpur", "Haflong", "Karimganj", 
            "Barpeta", "Dhemaji", "Bongaigaon", "Sonitpur", "Sivasagar", "Golaghat", "Cachar", 
            "Kokrajhar", "Lakhimpur", "Nalbari", "Darrang", "Kamrup", "Dhubri",
            "Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Darbhanga", "Munger", "Purnia", "Arrah", 
            "Siwan", "Sasaram", "Nalanda", "Katihar", "Begusarai", "Jehanabad", "Samastipur", "Chhapra", 
            "Buxar", "Kishanganj", "Madhubani", "Saran", "Gopalganj", "Bettiah",
            "Raipur", "Bilaspur", "Korba", "Durg", "Jagdalpur", "Raigarh", "Ambikapur", "Rajnandgaon", 
            "Janjgir-Champa", "Kanker", "Dhamtari", "Bemetara", "Kabirdham", "Baloda Bazar", "Gariaband", 
            "Surguja", "Mungeli", "Sukma", "Bijapur", "Balrampur",
            "Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda", "Quepem", "Cortalim", "Bicholim", 
            "Sanquelim", "Pernem", "Canacona", "Sanguem", "Kankon",
            "Ahmedabad", "Surat", "Vadodara", "Rajkot", "Junagadh", "Bhavnagar", "Gandhinagar", 
            "Anand", "Nadiad", "Mehsana", "Vapi", "Navsari", "Amreli", "Porbandar", "Kutch", "Patan", 
            "Jamnagar", "Bharuch", "Valsad", "Gir Somnath", "Dahod", "Surendranagar", "Aravalli", 
            "Kheda", "Mahesana", "Sabarkantha", "Palitana", "Modasa", "Narmada",
            "Faridabad", "Gurgaon", "Hisar", "Rohtak", "Ambala", "Karnal", "Panipat", "Yamunanagar", 
            "Jind", "Sirsa", "Kurukshetra", "Panchkula", "Mahendragarh", "Bhiwani", "Fatehabad", 
            "Rewari", "Nuh", "Palwal", "Kaithal", "Pehowa", "Tosham", "Hansi",
            "Shimla", "Manali", "Dharamshala", "Kullu", "Solan", "Hamirpur", "Mandi", "Kangra", 
            "Bilaspur", "Una", "Nahan", "Chamba", "Palampur", "Sundernagar",
            "Srinagar", "Jammu", "Udhampur", "Rajouri", "Kathua", "Anantnag", "Pulwama", "Baramulla", 
            "Kargil", "Leh", "Samba", "Doda", "Reasi", "Poonch", "Kupwara", "Bandipora",
            "Ranchi", "Jamshedpur", "Dhanbad", "Hazaribagh", "Giridih", "Bokaro", "Deoghar", 
            "Chaibasa", "Medininagar", "Koderma", "Daltonganj", "Jhumri Telaiya", "Raghubar Nagar", 
            "Ramgarh", "Jamtara", "Pakur", "Godda", "Sahebganj", "Dumka", "Palamu", "Giridih", 
            "Hazaribagh",
            "Bengaluru", "Mysuru", "Hubli", "Dharwad", "Mangalore", "Belgaum", "Shimoga", "Tumkur", 
            "Chitradurga", "Kolar", "Udupi", "Hassan", "Bagalkot", "Bijapur", "Bidar", "Raichur", 
            "Bellary", "Gulbarga", "Devadurga", "Yadgir", "Chikkamagalur", "Chikkaballapur", 
            "Mandya", "Haveri", "Kodagu", "Karwar", "Davangere", "Puttur", "Sagara", "Bantwal", 
            "Koppal", "Hospet", "Gadag", "Haveri", "Srinivaspur",
            "Thiruvananthapuram", "Kochi", "Kozhikode", "Kannur", "Palakkad", "Alappuzha", 
            "Malappuram", "Kottayam", "Idukki", "Ernakulam", "Wayanad", "Pathanamthitta", 
            "Kasaragod", "Ponnani", "Perinthalmanna", "Thrissur", "Changanassery", "Muvattupuzha", 
            "Attingal", "Varkala", "Sreekariyam",
            "Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain", "Sagar", "Satna", "Rewa", 
            "Ratlam", "Burhanpur", "Dewas", "Khargone", "Hoshangabad", "Shivpuri", "Mandsaur", 
            "Chhindwara", "Datiya", "Tikamgarh", "Ujjain", "Sehore", "Betul", "Jhabua", "Agar Malwa", 
            "Shahdol", "Anuppur", "Pachmarhi", "Khandwa",
            "Mumbai", "Pune", "Nagpur", "Aurangabad", "Nashik", "Thane", "Kolhapur", "Solapur", 
            "Amravati", "Jalgaon", "Latur", "Satara", "Ratnagiri", "Sindhudurg", "Raigad", "Palghar", 
            "Wardha", "Buldhana", "Akola", "Washim", "Yavatmal", "Osmanabad", "Jalna", "Parbhani", 
            "Beed", "Nanded", "Hingoli", "Dhule", "Jalgaon", "Nashik",
            "Imphal", "Shillong", "Aizawl", "Kohima", "Agartala", "Itanagar", "Dimapur", 
            "Lunglei", "Tura", "Churachandpur", "Silchar", "Kohima", "Mon", "Wokha",
            "Guwahati", "Silchar", "Dibrugarh", "Tezpur", "Jorhat", "Nagaon", "Karimganj", 
            "Hailakandi", "Kokrajhar", "Bongaigaon", "Dhemaji", "Golaghat", "Sivasagar", 
            "Barpeta", "Dhubri", "Nalbari", "Kamrup", "Kokrajhar", "Sonitpur", "Lakhimpur", 
            "Cachar", "Darrang", "Mikir Hills",
            "Lucknow", "Kanpur", "Agra", "Varanasi", "Allahabad", "Meerut", "Ghaziabad", "Noida", 
            "Aligarh", "Bareilly", "Mathura", "Moradabad", "Saharanpur", "Faizabad", "Ambedkar Nagar", 
            "Sultanpur", "Rae Bareli", "Etawah", "Mainpuri", "Unnao", "Mau", "Basti", "Jaunpur", 
            "Deoria", "Gorakhpur", "Firozabad", "Shahjahanpur", "Rampur", "Azamgarh", "Ballia", 
            "Bahraich", "Sitapur", "Hardoi", "Lakhimpur Kheri", "Gonda", "Siddharth Nagar", "Pilibhit",
            "Dehradun", "Haridwar", "Nainital", "Mussoorie", "Roorkee", "Haldwani", "Rudrapur", 
            "Kashipur", "Rishikesh", "Pauri", "Almora", "Bageshwar", "Champawat", "Uttarkashi", 
            "Tehri", "Pithoragarh", "Udham Singh Nagar",
            "Kolkata", "Howrah", "Darjeeling", "Siliguri", "Asansol", "Durgapur", "Kalyani", 
            "Bankura", "Murarai", "Haldia", "Malda", "Bardhaman", "Jamshedpur", "Durgapur", 
            "Purulia", "Krishnanagar", "Bongaigaon", "Jalpaiguri", "Midnapore", "Cooch Behar", 
            "Alipurduar"
]

legal_keywords = {
        'Contract': ['Payment Terms', 'Confidentiality', 'Agreement', 'Breach', 'Term', 'Consideration', 'Covenant', 'Obligations', 'Execution', 'Termination'],
        'Non-Disclosure Agreement': ['Confidentiality', 'Non-Disclosure', 'Proprietary Information', 'Trade Secrets', 'Disclosure', 'Recipient', 'Restricted', 'Confidential Information'],
        'Lease Agreement': ['Lease Term', 'Rent', 'Landlord', 'Tenant', 'Deposit', 'Premises', 'Maintenance', 'Utilities', 'Renewal', 'Termination'],
        'Employment Contract': ['Employment', 'Salary', 'Benefits', 'Job Title', 'Termination', 'Probation', 'Non-Compete', 'Work Hours', 'Duties', 'Confidentiality'],
        'Partnership Agreement': ['Partnership', 'Profit Sharing', 'Responsibilities', 'Contributions', 'Duties', 'Liabilities', 'Term', 'Dispute Resolution', 'Dissolution'],
        'Loan Agreement': ['Loan Amount', 'Interest Rate', 'Repayment Terms', 'Collateral', 'Default', 'Lender', 'Borrower', 'Principal', 'Amortization', 'Term'],
        'Service Agreement': ['Services', 'Deliverables', 'Scope of Work', 'Compensation', 'Performance', 'Terms', 'Termination', 'Liability', 'Indemnification', 'Warranties'],
        'Settlement Agreement': ['Settlement', 'Claims', 'Dispute', 'Compensation', 'Release', 'Terms', 'Agreement', 'Confidentiality', 'Payment', 'Resolution'],
        'Privacy Policy': ['Personal Data', 'Privacy', 'Data Collection', 'Usage', 'Disclosure', 'Security', 'Rights', 'Cookies', 'Third Parties', 'Compliance'],
        'Power of Attorney': ['Authority', 'Agent', 'Principal', 'Powers', 'Representation', 'Decision-Making', 'Legal', 'Termination', 'Revocation', 'Duties'],
        'Criminal Case': ['Defendant', 'Plaintiff', 'Charges', 'Evidence', 'Trial', 'Verdict', 'Prosecution', 'Defense', 'Sentencing', 'Appeal'],
        'Civil Case': ['Plaintiff', 'Defendant', 'Complaint', 'Evidence', 'Trial', 'Judgment', 'Settlement', 'Damages', 'Appeal', 'Liability'],
        'Divorce Case': ['Petitioner', 'Respondent', 'Custody', 'Alimony', 'Division of Assets', 'Settlement', 'Support', 'Visitation', 'Child Support', 'Dissolution'],
        'Property Case': ['Plaintiff', 'Defendant', 'Property Title', 'Lease', 'Possession', 'Easement', 'Boundary', 'Transfer', 'Sale', 'Ownership'],
        'Intellectual Property': ['Patent', 'Trademark', 'Copyright', 'Infringement', 'Licensing', 'Royalty', 'Patent Application', 'Trademark Registration', 'Creative Works', 'Protection'],
        'Bankruptcy': ['Debtor', 'Creditor', 'Filing', 'Discharge', 'Repayment Plan', 'Trustee', 'Chapter 7', 'Chapter 11', 'Chapter 13', 'Liquidation'],
        'Family Law': ['Custody', 'Support', 'Adoption', 'Guardianship', 'Marriage', 'Divorce', 'Paternity', 'Child Welfare', 'Protective Orders', 'Family Mediation'],
        'Immigration': ['Visa', 'Residency', 'Citizenship', 'Deportation', 'Green Card', 'Asylum', 'Work Permit', 'Naturalization', 'Immigration Status', 'Application'],
        'Contract Dispute': ['Breach', 'Enforcement', 'Remedies', 'Damages', 'Settlement', 'Negotiation', 'Contract Terms', 'Performance', 'Dispute Resolution', 'Mediation'],
        'Insurance Claim': ['Policy', 'Claim', 'Coverage', 'Exclusions', 'Premiums', 'Deductibles', 'Settlement', 'Claim Denial', 'Evidence', 'Payout'],
        'Traffic Violation': ['Citation', 'Ticket', 'Fine', 'Court Appearance', 'Violation', 'Penalty', 'Evidence', 'Defendant', 'Judge', 'Appeal'],
    }